import type { FooterSettings, SiteSettings } from '@/types/database'

export const SITE_SETTINGS_ID = '00000000-0000-0000-0000-000000000001'
export const FOOTER_SETTINGS_ID = '00000000-0000-0000-0000-000000000002'
export const ABOUT_PAGE_ID = '00000000-0000-0000-0000-000000000003'
export const CONTACT_PAGE_ID = '00000000-0000-0000-0000-000000000004'

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  id: SITE_SETTINGS_ID,
  site_title: 'National Mathematics Carnival 2026',
  competition_name: 'National Mathematics Carnival',
  competition_slug: 'nmc-2026',
  competition_category: 'Mathematics Competition',
  competition_season: '2026',
  competition_location: 'Dhaka, Bangladesh',
  organiser_name: 'Math Club, DUET',
  organiser_tagline: 'Celebrating Mathematical Excellence',
  logo_url: null,
  favicon_url: null,
  schedule_pdf_url: null,
  event_date: null,
  default_theme: 'light',
  use_static_theme: false,
  color_primary: '#4f46e5',
  color_secondary: '#7c3aed',
  color_accent: '#06b6d4',
  color_button_bg: '#4f46e5',
  color_button_text: '#ffffff',
  color_navbar_bg: '#ffffff',
  color_footer_bg: '#0f1117',
  footer_pattern: 'solid',
  font_heading: 'Playfair Display',
  font_body: 'Inter',
  animations_enabled: true,
  math_rain_enabled: true,
  math_rain_speed: 12,
  math_rain_color: 'rgba(79,70,229,0.18)',
  math_rain_size: 20,
  math_rain_count: 24,
  hero_mode: 'text',
  hero_title: 'National Mathematics Carnival 2026',
  hero_subtitle: '',
  hero_cta_label: 'View Events',
  hero_cta_url: '/events',
  hero_image_url: null,
  hero_carousel_images: [],
  hero_countdown_date: null,
  hero_show_countdown: true,
  hero_overlay_color: '#0f1117',
  hero_overlay_enabled: true,
  hero_overlay_opacity: 55,
  updated_at: new Date().toISOString(),
}

export const DEFAULT_FOOTER_SETTINGS: FooterSettings = {
  id: FOOTER_SETTINGS_ID,
  tagline: 'Celebrating Mathematical Excellence',
  organiser_text: 'Math Club, DUET',
  copyright_text: '© 2026 Math Club, DUET. All rights reserved.',
  developer_credit_text: 'Built by Math Club, DUET',
  developer_credit_url: null,
  show_developer_credit: true,
  show_privacy_link: false,
  privacy_url: null,
  show_terms_link: false,
  terms_url: null,
  contact_phone: null,
  contact_email: null,
  contact_address: null,
  show_phone: true,
  show_email: true,
  show_address: true,
  show_sponsor_strip: true,
  facebook_url: null,
  youtube_url: null,
  instagram_url: null,
  linkedin_url: null,
  twitter_url: null,
  show_facebook: true,
  show_youtube: true,
  show_instagram: true,
  show_linkedin: true,
  show_twitter: true,
  updated_at: new Date().toISOString(),
}
